# Spring properties
spring:
  application:
     name: order-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://104.154.168.97:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port