package com.google.gfx.model;

/**
 * A match to an existing order, generated by a user responding to a buy/sell order or by an cron
 * task that matches existing orders periodically.
 */
public class Match {

  /**
   * The buy order being matched.
   */
  private Order buyOrder;

  /**
   * The sell order being matched.
   */
  private Order sellOrder;

  /**
   * The exchange rate that applied to the currency being bought results in the amount of the
   * currency being sold.
   */
  private float fxRateBuyToSell;

  /**
   * The buyer's response. {@code true} if accepted, {@code false} is declined, or {@code null} if
   * non responded yet.
   */
  private Boolean buyerResponse;

  /**
   * The seller's response. {@code true} if accepted, {@code false} is declined, or {@code null} if
   * non responded yet.
   */
  private Boolean sellerResponse;

  /**
   * The final transactioned amount as part of this trade.
   */
  private float amount;

  public Match(Order buyOrder, Order sellOrder, float fxRateBuyToSell, Boolean buyerResponse,
               Boolean sellerResponse, float amount) {
    this.buyOrder = buyOrder;
    this.sellOrder = sellOrder;
    this.fxRateBuyToSell = fxRateBuyToSell;
    this.buyerResponse = buyerResponse;
    this.sellerResponse = sellerResponse;
    this.amount = amount;
  }
}
